# permissions for end users to view wxccoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wxccoperator-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - wxccoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - wxccoperators/status
  verbs:
  - get
